version: 2

workflows:
  version: 2
  release:
    jobs:
      - release:
          context: mysql-arm64-images
          filters:
            tags:
              only:
                - "/.*/"
            branches:
              ignore: /.*/

jobs:
  release:
    environment:
      CI: "true"
      BUILDKIT_PROGRESS: plain
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run: ./.circleci/linux_circle_vm_setup.sh
      - run: ls -lR xtrabackup-8.0/install
      - run: echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run: ./push.sh
      - run: docker logout
